In [2]:
import numpy as np




In [3]:
# Declaring Numpy array
a = np.array([1, 2, 3, 4, 5])

# Accessing array element (Indexing starts with 0)
a[2]

3

In [6]:
# Declaring 2 Dimentional array
a = np.array([[1, 2], [3, 4], [5, 6]])

In [7]:
# Number of Dimensions
a.ndim

2

In [8]:
# Number of rows and columns
a.shape

(3, 2)

In [10]:
# Size of element
a.itemsize # int so 4 bytes

4

In [11]:
# Data type
a.dtype

dtype('int32')

In [13]:
# Defining array with data type float
a = np.array([[1, 2], [3, 4], [5, 6]], dtype = np.float)

In [14]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [20]:
# Defining array with  placehoder numbers

# Zero's
z = np.zeros((2,3), dtype = int)
 # One's
o = np.ones((3,4), dtype = int)

In [29]:
# Reshaping the array
o.reshape(1,12)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [28]:
# Linearly spaced numbers 

# Below code generates the numbers the equal 10 numbers from 1 to 5
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [32]:
# Flatten the  array

a.ravel()

array([1., 2., 3., 4., 5., 6.])

In [33]:
a.min()

1.0

In [34]:
a.max()

6.0

In [35]:
a.sum()

21.0

In [36]:
a.std()

1.707825127659933

In [37]:
a.mean()

3.5

In [40]:
# Square Root
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [45]:
# Changing Float to int
a.astype(int)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
# array[rows, coulumns]

a[0:2]
# 0:2 prints all rows excluding last so it will print 0 and 1st rows

array([[1., 2.],
       [3., 4.]])

In [52]:
# accessing particular element
a[1,1] # row 1 and column 1 (Indexing starts with zero)

4.0

In [55]:
# Array and for loop
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

for row in a:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [58]:
# Printing each element
for row in a:
    for element in row:
        print(element)

1
2
3
4
5
6
7
8
9


In [64]:
# Array Flattening (a.flat or a.flatten())
for cell in a.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


In [69]:
# Array Range(arange) in Numpy
a = np.arange(6).reshape(3, 2)
b = np.arange(6, 12).reshape(3, 2)

In [70]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [71]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [72]:
# Vertical Stacking
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [73]:
# Horizantal Stacking
np.hstack((a, b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [90]:
# For Horizantal split and vertical split (Split in equal sizes only)
a = np.arange(20).reshape(2, 10)


In [91]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [92]:
# Horizantal
h = np.hsplit(a, 2)

In [93]:
h[0]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [94]:
h[1]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [95]:
# Vertical
v = np.vsplit(a, 2)

In [96]:
v[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [97]:
v[1]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [7]:
# Declaraing array

a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
# making True false array in which values are true if they are greater than 5
 b = a > 5

In [9]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [11]:
# making array of values whose value is grater than 5
c = a[b]

In [12]:
c

array([ 6,  7,  8,  9, 10, 11, 12])

In [14]:
# We can also replace true value by desired number( Here, values which are greater than 5 are replaced by -1)
a[b] = -1

In [15]:
a

array([[ 1,  2,  3,  4],
       [ 5, -1, -1, -1],
       [-1, -1, -1, -1]])

In [20]:
# iterate 2 array at a time
a = np.arange(1, 17).reshape(4, 4)
b = np.arange(16, 32).reshape(4, 4)
for x, y in np.nditer([a, b]):
    print(x+y)

17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47


In [24]:
# making operation on array
a = np.arange(1, 17).reshape(4, 4)
for x in np.nditer(a, op_flags = ['readwrite']):
    x[...] = x*x

In [25]:
a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])